#!/bin/bash
# Deploy script for copying project to remote H100 server

echo "🚀 XTTS Project Deployment to H100 Server"
echo "=========================================="

# Method 1: If you have the project in a Git repo (RECOMMENDED)
echo ""
echo "METHOD 1 - Git Clone (Recommended):"
echo "1. First, push your project to GitHub/GitLab:"
echo "   cd /c/Users/ual-laptop/Desktop/project"
echo "   git init"
echo "   git add ."
echo "   git commit -m 'Initial XTTS project setup'"
echo "   git remote add origin https://github.com/yourusername/xtts-project.git"
echo "   git push -u origin main"
echo ""
echo "2. Then on the H100 server:"
echo "   git clone https://github.com/yourusername/xtts-project.git"
echo "   cd xtts-project"

echo ""
echo "METHOD 2 - Direct SCP Transfer:"
echo "Replace USER@SERVER_IP with your actual server details"
echo ""
echo "# Compress and transfer the project"
echo "cd /c/Users/ual-laptop/Desktop"
echo "tar -czf xtts-project.tar.gz project/"
echo "scp xtts-project.tar.gz USER@SERVER_IP:~/"
echo ""
echo "# On the remote server:"
echo "tar -xzf xtts-project.tar.gz"
echo "cd project/"

echo ""
echo "METHOD 3 - Individual file transfer (if needed):"
echo "scp -r /c/Users/ual-laptop/Desktop/project USER@SERVER_IP:~/project"

echo ""
echo "🎯 H100 OPTIMIZED SETTINGS APPLIED:"
echo "✅ Batch size increased to 16 (from 8)"
echo "✅ Gradient accumulation reduced to 1 (from 2)" 
echo "✅ Max steps reduced to 2500 (larger batches = fewer steps needed)"
echo "✅ More frequent checkpoints (every 400 steps)"
echo "✅ More data loader workers (8 vs 4)"
echo "✅ Expected training time: 20-40 minutes (vs 45-90 on A100)"
echo ""
echo "💡 Cost Analysis:"
echo "H100: ~30 mins × $1.9/hour = ~$0.95"
echo "A100: ~70 mins × $1.4/hour = ~$1.63"
echo "H100 saves you ~$0.68 AND finishes 2x faster! 🚀"
